Task 3: add `cd` and `ls` commands
sloboegen98/SoftwareDesign-HW pull request #1
Opened 2021-03-21 13:24 UTC by sloboegen98

2021-04-04 03:07 UTC, aleksZubakov requested changes
В целом, весьма хорошо, поправьте стилистические мелочи, пока 8 баллов

2021-04-04 03:07 UTC, aleksZubakov commented on src/commands/builtin_commands.py
> +        return os.path.abspath(os.path.join(cur_path, new_path))
Мне кажется, что это все-таки лучше не к командам положить, а где-нибудь отдельно, т.к. все-таки это не утилита shell, а просто утильный метод

2021-04-04 03:07 UTC, aleksZubakov commented on src/commands/basic_commands.py
> +        directory = ''
Неиспользуемая переменная

2021-04-04 03:07 UTC, aleksZubakov commented on src/commands/basic_commands.py
> +                raise IOError(f'{directory}: is not exist or not is directory')
А почему не бросить сразу нормальное исключение? А то из-за вот этого лишний `try/except` приходится писать

2021-04-04 03:07 UTC, aleksZubakov commented on src/commands/basic_commands.py
> +        directory = ''
А, используемая, но явно лишнее объявление, оно и так будет работать

2021-04-09 06:50 UTC, sloboegen98 commented on testing/test_system.py
> +            'cd src',
Добавил просто новую директорию, которую, надеюсь, никто не будет трогать)

2021-04-09 06:51 UTC, sloboegen98 commented on src/enviroment/enviroment.py
> +        self._current_directory = new_dir
Хотелось отделить просто переменные питоновского интерпретатора от переменных моего интерпретатора. Но, в целом, легко переписывается без нее, так что поправил

2021-04-09 06:52 UTC, sloboegen98 commented on src/commands/basic_commands.py
> +                raise IOError(f'{directory}: is not exist or not is directory')
После отказа использования переменной `current_directory` питоновская `os.chdir` сама теперь все делает

2021-04-15 14:21 UTC, aleksZubakov commented on src/enviroment/enviroment.py
> +        self._current_directory = new_dir
Стоило оставить это переменной окружения, у этого больше преимуществ, чем у использования `os.chdir`, элементарно хотя бы из-за удобности тестировать, но ок

2021-04-15 14:21 UTC, aleksZubakov commented
Исправления засчитываю

2021-04-15 14:21 UTC, closed without merging